source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Spinner_Example', :exclusive => true do
  pod 'Spinner', :path => '../'
end

target 'Spinner_Tests', :exclusive => true do
  pod 'Spinner', :path => '../'

  
end
